### ISSUE TITLE
P1のdocker起動時volumeオプション

### ISSUE THREAD

**Issue by sota0113** [zoetrope/etcd-book#1]
P1のコマンド例では以下のvolumeオプションで起動しています。
```
--volume=etcd-data:/etcd-data
```
一方直後の解説では、volumeオプションが以下で書かれています。
```
-v etcd-data:/var/lib/etcd
```
どちらが正でしょうか？

**Comment by zoetrope** [comment]
ながらく放置してすみません。修正しました。
https://github.com/zoetrope/etcd-book/commit/cbc69dad9e76265ee4707de3f186170b0a353790
